# Generated by Django 5.2.11 on 2026-02-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='qtde',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
